import type { GameCard } from "./types"
const spell = (
  card: Pick<GameCard, "id" | "name" | "school" | "cost" | "effect" | "power" | "text" | "lore" | "art"> & Partial<GameCard>,
): GameCard => ({
  kind: "spell",
  rarity: "rare",
  attack: 0,
  health: 0,
  keywords: [],
  symbol: "✦",
  set: "Chợ Ký Ức Sống",
  contentVersion: 400,
  ...card,
})
export const V4_CARDS: GameCard[] = [
  spell({
    id: "v4-crossroads-tea",
    name: "Ấm trà ngã rẽ",
    school: "tide",
    cost: 2,
    effect: "draw",
    power: 1,
    text: "Nêm vị — chọn một: hồi 4 ý chí và 1 máu mỗi đồng minh; hoặc rút 1 lá.",
    lore: "Một ấm trà đủ cho người cần nghỉ và người muốn lên đường.",
    art: "/assets/tcg/cards/herb.webp",
    choices: [
      {
        label: "Mời ngồi lại",
        text: "Hồi 4 ý chí và 1 máu mỗi đồng minh.",
        effect: "heal",
        ability: "tea-mend",
        power: 4,
      },
      {
        label: "Gói mang theo",
        text: "Rút 1 lá, tính là một phép.",
        effect: "draw",
        power: 1,
      },
    ],
  }),
  spell({
    id: "v4-two-spices",
    name: "Hai nhúm gia vị",
    school: "ember",
    cost: 2,
    effect: "ward",
    power: 2,
    text: "Nêm vị — chọn một: gây 3 sát thương lên một mục tiêu địch; hoặc đội bạn nhận 2 chắn.",
    lore: "Nhiên không đo lòng can đảm bằng việc dùng hết ớt.",
    art: "/assets/tcg/cards/spark.webp",
    choices: [
      {
        label: "Dậy lửa",
        text: "Gây 3 sát thương lên một mục tiêu địch.",
        effect: "damage",
        power: 3,
      },
      {
        label: "Giữ bếp",
        text: "Mọi đồng minh nhận 2 chắn.",
        effect: "ward",
        power: 2,
      },
    ],
  }),
  spell({
    id: "v4-moon-token",
    name: "Đèn của người đi tiếp",
    school: "sugar",
    cost: 3,
    effect: "heal",
    power: 4,
    text: "Nêm vị — chọn một: gọi lại đồng minh giá tối đa 4 với 2 máu; hoặc hồi 4 ý chí và đóng băng địch công cao nhất.",
    lore: "Liên giữ đèn cho những bước chân thật, không gọi người đã mất trở về.",
    art: "/assets/tcg/cards/sugar-veil.webp",
    choices: [
      {
        label: "Nối ký ức",
        text: "Tái triệu hồi một đồng minh giá tối đa 4 với 2 máu; chưa được đánh.",
        effect: "draw",
        ability: "revive",
        power: 0,
      },
      {
        label: "Giữ khoảng lặng",
        text: "Hồi 4 ý chí; địch công cao nhất bỏ một đòn.",
        effect: "heal",
        ability: "dream",
        power: 4,
      },
    ],
  }),
  spell({
    id: "v4-banked-coals",
    name: "Nồi than ủ",
    school: "hearth",
    cost: 2,
    effect: "buff",
    power: 2,
    ability: "steep-unit",
    text: "Ủ vị — đồng minh ít máu nhất nhận +2 công/+2 máu đầu lượt sau nếu còn sống. Tối đa 2 hiệu ứng chờ mỗi phe.",
    lore: "Giữ lửa là tin người bên bếp còn có thời gian để lựa chọn.",
    art: "/assets/tcg/cards/seasoning.webp",
  }),
  spell({
    id: "v4-rain-seed",
    name: "Chậu mầm bên bếp",
    school: "grove",
    cost: 3,
    effect: "heal",
    power: 4,
    ability: "steep-heal",
    text: "Ủ vị — đầu lượt sau hồi 4 ý chí và 2 máu mỗi đồng minh. Có thể bị gỡ trước khi nở.",
    lore: "Mộc không viết tên người đã mất lên một mầm cây mới.",
    art: "/assets/tcg/cards/herb.webp",
  }),
  spell({
    id: "v4-unseal-recipe",
    name: "Mở nắp đúng lúc",
    school: "tide",
    cost: 2,
    effect: "draw",
    power: 0,
    ability: "unsteep",
    text: "Chọn và gỡ đúng một Ủ vị đang chờ của địch. Không hoàn lại năng lượng cho họ.",
    lore: "Hải nghe tiếng nồi trước khi nước trào.",
    art: "/assets/tcg/cards/sea-memory.webp",
  }),
  spell({
    id: "v4-warm-towel",
    name: "Khăn ấm sau mưa",
    school: "grove",
    cost: 2,
    effect: "heal",
    power: 2,
    ability: "thaw",
    text: "Đội bạn được giải đóng băng và hồi 2 máu mỗi đồng minh. Quân bỏ đòn vì băng ở lượt này được sẵn sàng lại.",
    lore: "Bà Sen không hỏi ai đã nấu sai trước khi đưa chiếc khăn khô.",
    art: "/assets/tcg/cards/herb.webp",
  }),
  {
    id: "v4-market-host",
    name: "Người kể bên bàn",
    school: "sugar",
    rarity: "rare",
    kind: "unit",
    cost: 3,
    attack: 2,
    health: 4,
    keywords: [],
    ability: "season-host",
    contentVersion: 400,
    text: "Sau khi bạn giải quyết một Nêm vị, rút 1 lá. Tối đa một lần mỗi lượt của bạn.",
    lore: "Câu chuyện hay để lại chỗ cho giọng kể kế tiếp.",
    symbol: "✧",
    set: "Chợ Ký Ức Sống",
    art: "/assets/tcg/characters/anime/lien.webp",
  },
]
export function flavoredCard(
  card: GameCard,
  branch?: "first" | "second",
): GameCard {
  const choice = branch ? card.choices?.[branch === "first" ? 0 : 1] : undefined
  return choice
    ? {
        ...card,
        effect: choice.effect,
        power: choice.power,
        ability: choice.ability,
        text: choice.text,
      }
    : card
}
export const cardBranches = (
  card: GameCard,
): ("first" | "second" | undefined)[] =>
  card.choices ? ["first", "second"] : [undefined]
