import { Dish } from "../../domain/models"

export const SEED_DISHES: Dish[] = [
  {
    id: "pho-bo",
    name: "Phở bò",
    searchQuery: "phở bò",
    mealSlots: ["breakfast", "lunch"],
    category: "noodle",
    description: "Phở bò nóng với nước dùng thơm",
    tags: ["vietnamese", "hot"],
    weight: 100,
    active: true,
    minRating: 4.0,
    minReviews: 30,
  },
  {
    id: "pho-ga",
    name: "Phở gà",
    searchQuery: "phở gà",
    mealSlots: ["breakfast", "lunch"],
    category: "noodle",
    description: "Phở gà thanh nhẹ",
    tags: ["vietnamese", "hot"],
    weight: 100,
    active: true,
    minRating: 4.0,
    minReviews: 20,
  },
  {
    id: "bun-rieu",
    name: "Bún riêu",
    searchQuery: "bún riêu cua",
    mealSlots: ["breakfast", "lunch"],
    category: "noodle",
    description: "Bún riêu cua cà chua",
    tags: ["vietnamese", "hot"],
    weight: 100,
    active: true,
    minRating: 4.0,
    minReviews: 20,
  },
  {
    id: "bun-bo-hue",
    name: "Bún bò Huế",
    searchQuery: "bún bò Huế",
    mealSlots: ["breakfast", "lunch", "dinner"],
    category: "noodle",
    description: "Bún bò vị đậm và cay nhẹ",
    tags: ["vietnamese", "spicy"],
    weight: 100,
    active: true,
    minRating: 4.0,
    minReviews: 30,
  },
  {
    id: "banh-mi",
    name: "Bánh mì",
    searchQuery: "bánh mì",
    mealSlots: ["breakfast", "lunch"],
    category: "bread",
    description: "Bánh mì kẹp nhanh gọn",
    tags: ["vietnamese", "quick"],
    weight: 100,
    active: true,
    minRating: 4.0,
    minReviews: 20,
  },
  {
    id: "xoi",
    name: "Xôi mặn",
    searchQuery: "xôi mặn",
    mealSlots: ["breakfast"],
    category: "rice",
    description: "Xôi ăn sáng no lâu",
    tags: ["vietnamese", "quick"],
    weight: 100,
    active: true,
    minRating: 4.0,
    minReviews: 15,
  },
  {
    id: "banh-cuon",
    name: "Bánh cuốn",
    searchQuery: "bánh cuốn",
    mealSlots: ["breakfast"],
    category: "rice-roll",
    description: "Bánh cuốn nóng mềm",
    tags: ["vietnamese"],
    weight: 100,
    active: true,
    minRating: 4.0,
    minReviews: 20,
  },
  {
    id: "chao-suon",
    name: "Cháo sườn",
    searchQuery: "cháo sườn",
    mealSlots: ["breakfast", "dinner"],
    category: "porridge",
    description: "Cháo mịn ăn kèm quẩy",
    tags: ["vietnamese", "hot"],
    weight: 100,
    active: true,
    minRating: 4.0,
    minReviews: 20,
  },
  {
    id: "mien-ga",
    name: "Miến gà",
    searchQuery: "miến gà",
    mealSlots: ["breakfast", "lunch", "dinner"],
    category: "noodle",
    description: "Miến gà nước hoặc trộn",
    tags: ["vietnamese"],
    weight: 100,
    active: true,
    minRating: 4.0,
    minReviews: 20,
  },
  {
    id: "bun-moc",
    name: "Bún mọc",
    searchQuery: "bún mọc",
    mealSlots: ["breakfast", "lunch"],
    category: "noodle",
    description: "Bún mọc thanh vị",
    tags: ["vietnamese"],
    weight: 100,
    active: true,
    minRating: 4.0,
    minReviews: 20,
  },
  {
    id: "banh-da-cua",
    name: "Bánh đa cua",
    searchQuery: "bánh đa cua",
    mealSlots: ["lunch", "dinner"],
    category: "noodle",
    description: "Bánh đa đỏ cùng riêu cua",
    tags: ["vietnamese"],
    weight: 100,
    active: true,
    minRating: 4.0,
    minReviews: 20,
  },
  {
    id: "bun-cha",
    name: "Bún chả",
    searchQuery: "bún chả",
    mealSlots: ["lunch", "dinner"],
    category: "noodle",
    description: "Bún chả nướng kiểu Hà Nội",
    tags: ["vietnamese", "grilled"],
    weight: 100,
    active: true,
    minRating: 4.0,
    minReviews: 30,
  },
  {
    id: "bun-dau",
    name: "Bún đậu mắm tôm",
    searchQuery: "bún đậu mắm tôm",
    mealSlots: ["lunch", "dinner"],
    category: "combo",
    description: "Mẹt bún đậu nhiều topping",
    tags: ["vietnamese"],
    weight: 100,
    active: true,
    minRating: 4.0,
    minReviews: 30,
  },
  {
    id: "com-tam",
    name: "Cơm tấm",
    searchQuery: "cơm tấm sườn nướng",
    mealSlots: ["lunch", "dinner"],
    category: "rice",
    description: "Cơm tấm cùng sườn nướng",
    tags: ["vietnamese", "grilled"],
    weight: 100,
    active: true,
    minRating: 4.0,
    minReviews: 30,
  },
  {
    id: "com-ga",
    name: "Cơm gà",
    searchQuery: "cơm gà",
    mealSlots: ["lunch", "dinner"],
    category: "rice",
    description: "Cơm gà tiện cho bữa chính",
    tags: ["vietnamese"],
    weight: 100,
    active: true,
    minRating: 4.0,
    minReviews: 20,
  },
  {
    id: "com-rang-dua-bo",
    name: "Cơm rang dưa bò",
    searchQuery: "cơm rang dưa bò",
    mealSlots: ["lunch", "dinner"],
    category: "rice",
    description: "Cơm rang nóng với dưa bò",
    tags: ["vietnamese"],
    weight: 100,
    active: true,
    minRating: 4.0,
    minReviews: 20,
  },
  {
    id: "com-nieu",
    name: "Cơm niêu",
    searchQuery: "cơm niêu",
    mealSlots: ["lunch", "dinner"],
    category: "rice",
    description: "Cơm niêu cho bữa ăn đầy đặn",
    tags: ["vietnamese", "group"],
    weight: 80,
    active: true,
    minRating: 4.0,
    minReviews: 30,
  },
  {
    id: "bun-ca",
    name: "Bún cá",
    searchQuery: "bún cá",
    mealSlots: ["lunch", "dinner"],
    category: "noodle",
    description: "Bún cá chiên hoặc cá rô",
    tags: ["vietnamese"],
    weight: 100,
    active: true,
    minRating: 4.0,
    minReviews: 20,
  },
  {
    id: "mi-van-than",
    name: "Mì vằn thắn",
    searchQuery: "mì vằn thắn",
    mealSlots: ["breakfast", "lunch", "dinner"],
    category: "noodle",
    description: "Mì với sủi cảo và xá xíu",
    tags: ["chinese", "hot"],
    weight: 90,
    active: true,
    minRating: 4.0,
    minReviews: 20,
  },
  {
    id: "mi-cay",
    name: "Mì cay",
    searchQuery: "mì cay",
    mealSlots: ["lunch", "dinner"],
    category: "noodle",
    description: "Mì cay nhiều cấp độ",
    tags: ["korean", "spicy"],
    weight: 80,
    active: true,
    minRating: 4.0,
    minReviews: 30,
  },
  {
    id: "ga-ran",
    name: "Gà rán",
    searchQuery: "gà rán",
    mealSlots: ["lunch", "dinner"],
    category: "fast-food",
    description: "Gà chiên giòn dễ ăn",
    tags: ["fried", "quick"],
    weight: 80,
    active: true,
    minRating: 4.0,
    minReviews: 30,
  },
  {
    id: "pizza",
    name: "Pizza",
    searchQuery: "pizza",
    mealSlots: ["lunch", "dinner"],
    category: "western",
    description: "Pizza phù hợp đi nhóm",
    tags: ["western", "group"],
    weight: 70,
    active: true,
    minRating: 4.0,
    minReviews: 50,
  },
  {
    id: "pasta",
    name: "Mì Ý",
    searchQuery: "mì Ý pasta",
    mealSlots: ["lunch", "dinner"],
    category: "western",
    description: "Pasta sốt kem hoặc cà chua",
    tags: ["western"],
    weight: 70,
    active: true,
    minRating: 4.0,
    minReviews: 30,
  },
  {
    id: "sushi",
    name: "Sushi",
    searchQuery: "sushi",
    mealSlots: ["lunch", "dinner"],
    category: "japanese",
    description: "Cơm cuộn và hải sản Nhật",
    tags: ["japanese"],
    weight: 70,
    active: true,
    minRating: 4.0,
    minReviews: 50,
  },
  {
    id: "tokbokki",
    name: "Tokbokki",
    searchQuery: "tokbokki",
    mealSlots: ["lunch", "dinner"],
    category: "korean",
    description: "Bánh gạo Hàn Quốc cay ngọt",
    tags: ["korean", "spicy"],
    weight: 80,
    active: true,
    minRating: 4.0,
    minReviews: 20,
  },
  {
    id: "lau-thai",
    name: "Lẩu Thái",
    searchQuery: "lẩu Thái",
    mealSlots: ["dinner"],
    category: "hotpot",
    description: "Lẩu chua cay phù hợp đi nhóm",
    tags: ["thai", "group", "spicy"],
    weight: 60,
    active: true,
    minRating: 4.0,
    minReviews: 50,
  },
  {
    id: "lau-rieu-cua",
    name: "Lẩu riêu cua",
    searchQuery: "lẩu riêu cua",
    mealSlots: ["dinner"],
    category: "hotpot",
    description: "Lẩu riêu cua đậm vị",
    tags: ["vietnamese", "group"],
    weight: 60,
    active: true,
    minRating: 4.0,
    minReviews: 40,
  },
  {
    id: "nuong-bbq",
    name: "Nướng BBQ",
    searchQuery: "quán nướng BBQ",
    mealSlots: ["dinner"],
    category: "grilled",
    description: "Đồ nướng cho buổi tối",
    tags: ["grilled", "group"],
    weight: 60,
    active: true,
    minRating: 4.0,
    minReviews: 50,
  },
  {
    id: "vit-quay",
    name: "Vịt quay",
    searchQuery: "vịt quay",
    mealSlots: ["lunch", "dinner"],
    category: "roast",
    description: "Vịt quay da giòn",
    tags: ["vietnamese", "chinese"],
    weight: 80,
    active: true,
    minRating: 4.0,
    minReviews: 30,
  },
  {
    id: "banh-xeo",
    name: "Bánh xèo",
    searchQuery: "bánh xèo",
    mealSlots: ["lunch", "dinner"],
    category: "pancake",
    description: "Bánh xèo giòn ăn cùng rau",
    tags: ["vietnamese"],
    weight: 90,
    active: true,
    minRating: 4.0,
    minReviews: 20,
  },
  {
    id: "bibimbap",
    name: "Bibimbap",
    searchQuery: "bibimbap Hàn Quốc",
    mealSlots: ["lunch", "dinner"],
    category: "korean",
    description: "Cơm trộn Hàn Quốc nhiều rau, bò và trứng",
    tags: ["korean", "rice"],
    weight: 90,
    rarity: "common",
    priceTier: 2,
    active: true,
    minRating: 4.1,
    minReviews: 30,
  },
  {
    id: "samgyeopsal",
    name: "Samgyeopsal",
    searchQuery: "thịt nướng samgyeopsal Hàn Quốc",
    mealSlots: ["lunch", "dinner"],
    category: "korean-bbq",
    description: "Ba chỉ nướng Hàn Quốc ăn cùng rau cuốn",
    tags: ["korean", "grilled", "group"],
    weight: 48,
    rarity: "rare",
    priceTier: 3,
    active: true,
    minRating: 4.2,
    minReviews: 50,
  },
  {
    id: "hanwoo-bbq",
    name: "Hanwoo BBQ",
    searchQuery: "Hanwoo beef BBQ fine dining",
    mealSlots: ["dinner"],
    category: "korean-fine-dining",
    description: "Thịt bò Hanwoo vân mỡ cao cấp",
    tags: ["korean", "fine-dining", "occasion"],
    weight: 6,
    rarity: "diamond",
    priceTier: 4,
    active: true,
    minRating: 4.5,
    minReviews: 80,
  },
  {
    id: "shoyu-ramen",
    name: "Shoyu Ramen",
    searchQuery: "shoyu ramen Nhật Bản",
    mealSlots: ["lunch", "dinner"],
    category: "japanese",
    description: "Ramen nước tương với chashu và trứng lòng đào",
    tags: ["japanese", "noodle", "hot"],
    weight: 85,
    rarity: "common",
    priceTier: 2,
    active: true,
    minRating: 4.1,
    minReviews: 40,
  },
  {
    id: "unagi-don",
    name: "Unagi Don",
    searchQuery: "cơm lươn Nhật unagi don",
    mealSlots: ["lunch", "dinner"],
    category: "japanese",
    description: "Lươn nướng sốt tare trên cơm Nhật",
    tags: ["japanese", "premium", "rice"],
    weight: 24,
    rarity: "epic",
    priceTier: 3,
    active: true,
    minRating: 4.3,
    minReviews: 50,
  },
  {
    id: "omakase",
    name: "Omakase",
    searchQuery: "omakase fine dining",
    mealSlots: ["dinner"],
    category: "japanese-fine-dining",
    description: "Trải nghiệm thực đơn Nhật theo lựa chọn của đầu bếp",
    tags: ["japanese", "fine-dining", "occasion"],
    weight: 5,
    rarity: "diamond",
    priceTier: 4,
    active: true,
    minRating: 4.5,
    minReviews: 60,
  },
  {
    id: "lasagna",
    name: "Lasagna",
    searchQuery: "lasagna Ý",
    mealSlots: ["lunch", "dinner"],
    category: "italian",
    description: "Mì lá nướng nhiều lớp ragù và phô mai",
    tags: ["italian", "baked"],
    weight: 60,
    rarity: "rare",
    priceTier: 2,
    active: true,
    minRating: 4.1,
    minReviews: 30,
  },
  {
    id: "truffle-risotto",
    name: "Risotto nấm Truffle",
    searchQuery: "truffle risotto fine dining",
    mealSlots: ["dinner"],
    category: "italian-premium",
    description: "Risotto kem Parmesan cùng nấm truffle",
    tags: ["italian", "premium", "fine-dining"],
    weight: 20,
    rarity: "epic",
    priceTier: 3,
    active: true,
    minRating: 4.3,
    minReviews: 30,
  },
  {
    id: "bistecca-fiorentina",
    name: "Bistecca Fiorentina",
    searchQuery: "bistecca alla fiorentina steak",
    mealSlots: ["dinner"],
    category: "italian-fine-dining",
    description: "Bít tết T-bone kiểu Tuscany cho dịp đặc biệt",
    tags: ["italian", "steak", "occasion"],
    weight: 7,
    rarity: "diamond",
    priceTier: 4,
    active: true,
    minRating: 4.5,
    minReviews: 50,
  },
  {
    id: "croissant",
    name: "Croissant bơ",
    searchQuery: "croissant Pháp",
    mealSlots: ["breakfast"],
    category: "french-bakery",
    description: "Bánh sừng bò bơ nhiều lớp giòn thơm",
    tags: ["french", "bakery", "breakfast"],
    weight: 92,
    rarity: "common",
    priceTier: 1,
    active: true,
    minRating: 4.0,
    minReviews: 20,
  },
  {
    id: "duck-confit",
    name: "Duck Confit",
    searchQuery: "duck confit Pháp",
    mealSlots: ["dinner"],
    category: "french",
    description: "Đùi vịt confit da giòn cùng sốt vang",
    tags: ["french", "premium"],
    weight: 25,
    rarity: "epic",
    priceTier: 3,
    active: true,
    minRating: 4.3,
    minReviews: 30,
  },
  {
    id: "french-tasting",
    name: "French Tasting Menu",
    searchQuery: "French fine dining tasting menu",
    mealSlots: ["dinner"],
    category: "french-fine-dining",
    description: "Thực đơn fine dining Pháp nhiều món cho dịp đặc biệt",
    tags: ["french", "fine-dining", "occasion"],
    weight: 4,
    rarity: "diamond",
    priceTier: 4,
    active: true,
    minRating: 4.6,
    minReviews: 50,
  },
  {
    id: "classic-burger",
    name: "Classic Cheeseburger",
    searchQuery: "classic cheeseburger",
    mealSlots: ["lunch", "dinner"],
    category: "american",
    description: "Burger bò phô mai kiểu Mỹ cùng khoai chiên",
    tags: ["american", "fast-food"],
    weight: 82,
    rarity: "common",
    priceTier: 2,
    active: true,
    minRating: 4.0,
    minReviews: 40,
  },
  {
    id: "smoked-brisket",
    name: "Smoked Brisket",
    searchQuery: "smoked brisket BBQ",
    mealSlots: ["lunch", "dinner"],
    category: "american-bbq",
    description: "Ức bò hun khói chậm với lớp bark đậm vị",
    tags: ["american", "bbq", "premium"],
    weight: 45,
    rarity: "rare",
    priceTier: 3,
    active: true,
    minRating: 4.2,
    minReviews: 40,
  },
  {
    id: "xiaolongbao",
    name: "Xiaolongbao",
    searchQuery: "xiaolongbao tiểu long bao",
    mealSlots: ["breakfast", "lunch", "dinner"],
    category: "chinese",
    description: "Tiểu long bao nhân thịt và nước súp",
    tags: ["chinese", "dumpling"],
    weight: 55,
    rarity: "rare",
    priceTier: 2,
    active: true,
    minRating: 4.1,
    minReviews: 30,
  },
  {
    id: "peking-duck",
    name: "Vịt quay Bắc Kinh",
    searchQuery: "vịt quay Bắc Kinh Peking duck",
    mealSlots: ["lunch", "dinner"],
    category: "chinese-premium",
    description: "Vịt da giòn ăn cùng bánh cuốn và sốt hoisin",
    tags: ["chinese", "premium", "group"],
    weight: 22,
    rarity: "epic",
    priceTier: 3,
    active: true,
    minRating: 4.3,
    minReviews: 50,
  },
  {
    id: "haidilao-hotpot",
    name: "Lẩu Haidilao",
    searchQuery: "Haidilao hotpot",
    mealSlots: ["dinner"],
    category: "chinese-premium-hotpot",
    description: "Bữa lẩu cao cấp cho nhóm và dịp đặc biệt",
    tags: ["chinese", "hotpot", "occasion", "group"],
    weight: 8,
    rarity: "diamond",
    priceTier: 4,
    active: true,
    minRating: 4.4,
    minReviews: 100,
  },
  {
    id: "pad-thai",
    name: "Pad Thai",
    searchQuery: "pad thai Thái Lan",
    mealSlots: ["lunch", "dinner"],
    category: "thai",
    description: "Phở xào Thái cùng tôm, trứng và lạc",
    tags: ["thai", "noodle"],
    weight: 80,
    rarity: "common",
    priceTier: 2,
    active: true,
    minRating: 4.1,
    minReviews: 30,
  },
  {
    id: "tom-yum-goong",
    name: "Tom Yum Goong",
    searchQuery: "tom yum goong Thái Lan",
    mealSlots: ["lunch", "dinner"],
    category: "thai-premium",
    description: "Canh tôm chua cay thơm sả và lá chanh",
    tags: ["thai", "spicy", "premium"],
    weight: 28,
    rarity: "epic",
    priceTier: 3,
    active: true,
    minRating: 4.3,
    minReviews: 40,
  },
  {
    id: "mango-sticky-rice",
    name: "Xôi xoài Thái",
    searchQuery: "mango sticky rice xôi xoài Thái",
    mealSlots: ["breakfast", "lunch", "dinner"],
    category: "thai-dessert",
    description: "Xôi nếp cốt dừa ăn cùng xoài chín",
    tags: ["thai", "dessert"],
    weight: 65,
    rarity: "rare",
    priceTier: 2,
    active: true,
    minRating: 4.1,
    minReviews: 25,
  },
]
