import { useAppStore } from "../store/useAppStore"

export type Language = "vi" | "en"

const translations = {
  vi: {
    chest: "Rương vị giác", collection: "Bộ sưu tập", achievements: "Thành tựu", wheel: "Vòng quay", settings: "Cài đặt",
    today: "Hôm nay", checkIn: "Điểm danh nhận chìa", checkedIn: "Đã điểm danh", comeBackTomorrow: "Quay lại vào ngày mai",
    keys: "chìa khóa", rewards: "phần thưởng", fusions: "lần ghép", dailyQuest: "NHIỆM VỤ MỖI 3 GIỜ", limitedEvent: "SỰ KIỆN GIỚI HẠN", weeklyEvent: "SỰ KIỆN TUẦN",
    freeChest: "Rương miễn phí", collectionFoods: "Bộ sưu tập món", extendedAchievements: "THÀNH TỰU MỞ RỘNG", achievementProfile: "Hồ sơ chiến tích", streak: "Ngày liên tiếp",
    sound: "Âm thanh nghi thức", reducedMotion: "Giảm chuyển động", language: "Ngôn ngữ", vietnamese: "Tiếng Việt", english: "English",
    addDish: "Thêm món local", catalog: "Nguồn dữ liệu món ăn", keyHistory: "Lịch sử chìa khóa", save: "Lưu", close: "Đóng", cancel: "Hủy", mealBreakfast: "Bữa sáng", mealLunch: "Bữa trưa", mealDinner: "Bữa tối", dailyOnce: "Mỗi ngày một lần", soundOn: "Tắt âm thanh", soundOff: "Bật âm thanh", unlimitedChest: "Rương vô hạn", keyShort: "CHÌA", deleteDish: "Xóa món", replaceImage: "Đổi ảnh", uploadingImage: "Đang xử lý ảnh...", confirmDelete: "Xóa món này khỏi catalog local?",
    brandTitle: "RƯƠNG VỊ GIÁC", brandSubtitle: "Mở rương, chốt món", useLocation: "Dùng vị trí hiện tại của tôi", locationLoading: "Đang lấy vị trí...", locationDenied: "Quyền vị trí bị từ chối.", locationError: "Không lấy được vị trí.", enterArea: "Nhập khu vực để tìm kiếm:", tryAgain: "Thử lại", search: "Tìm", nearbyRestaurants: "Gần vị trí của bạn", findRestaurants: "Tìm quán gần đây", openMaps: "Mở Maps", directions: "Chỉ đường", openNow: "Đang mở", nearTwoKm: "≤ 2 km", noPlaces: "Không tìm thấy quán đủ tiêu chí.", noFilterResults: "Không có quán khớp bộ lọc.", clearFilters: "Bỏ bộ lọc", mapsFallback: "Mở Maps thay thế", locationSearchPlaceholder: "Quận 1, TP.HCM...", unknownRating: "Chưa có rating/review", dataFromOsm: "Dữ liệu từ OpenStreetMap · rating/review không có trong nguồn này.", dataFromGoogle: "Dữ liệu từ Google Maps", openMapLink: "Tìm trên Google Maps →", openAgain: "Mở tiếp", noKeysCheckIn: "Hết chìa · Điểm danh ngày mai để nhận thêm",
    sunrise: "BÌNH MINH", sunriseSubtitle: "Món ngon khởi đầu ngày mới", daylight: "THIÊN QUANG", daylightSubtitle: "Nạp năng lượng giữa ngày", dusk: "DẠ YẾN", duskSubtitle: "Khép ngày bằng một lựa chọn xứng đáng", readyState: "Sẵn sàng khai mở", keyFlight: "Chìa khóa đang cộng hưởng", inserting: "Kích hoạt lõi vị giác", locking: "Khóa cổ ngữ đã khớp", charging: "Tích tụ năng lượng", pulse: "Cộng hưởng cực đại", anticipation: "Lắng nghe khoảnh khắc thức tỉnh", impact: "Khai mở!", opening: "Rương đã mở", rewardRise: "Triệu hồi món ăn", result: "Đã nhận phần thưởng", chestHeading: "ĐÁNH THỨC LỰA CHỌN", chestHeadingYour: "CỦA BẠN", openChest: "KHAI MỞ RƯƠNG", energyGathering: "Năng lượng đang hội tụ", unlimitedCost: "ĐẶC QUYỀN VÔ HẠN · KHÔNG TỐN CHÌA", keyCost: "TIÊU HAO 1 CHÌA KHÓA", skipScene: "Bỏ qua hoạt cảnh", skipNext: "Bỏ qua hoạt cảnh lần sau", todayDishes: "HÔM NAY", dishes: "MÓN", rarityRate: "TỶ LỆ HIẾM", viewOdds: "XEM TỈ LỆ", goldenHour: "GIỜ VÀNG · Cơ hội món Rare+ tăng trong khung 18:00–21:00", freeChestReady: "Rương miễn phí hôm nay", freeChestUsed: "Đã dùng rương miễn phí", noKey: "Không tốn chìa khóa", returnTomorrow: "Quay lại vào ngày mai", open: "MỞ", share: "Chia sẻ", favorite: "Yêu thích", favorited: "Đã yêu thích", fusion: "Ghép món", unlockedReward: "PHẦN THƯỞNG ĐÃ ĐƯỢC KHAI MỞ", copyResult: "Đã sao chép kết quả!", shareError: "Không thể chia sẻ kết quả.", downloadCard: "Card", downloadedCard: "Đã tải share card!", dismiss: "Đóng", retrySearch: "Thử lại sau hoặc mở Google Maps.", placeSearchTitle: "Quán", filterDataNote: "Bộ lọc đang mở và khoảng cách vẫn hoạt động.", restaurantOpen: "Mở", restaurantClosed: "Đóng", loadingRestaurants: "Đang tìm quán ngon gần bạn...", collectionJourney: "HÀNH TRÌNH SƯU TẦM", achievementTitle: "Thành tựu Vị Giác", achievementDescription: "Mở mỗi món ít nhất một lần. Hoàn thành toàn bộ danh mục để mở khóa rương vô hạn vĩnh viễn trên thiết bị này.", unlimitedUnlocked: "RƯƠNG VÔ HẠN ĐÃ MỞ", wholeReward: "PHẦN THƯỞNG TOÀN BỘ", noKeyCost: "Không còn tiêu hao chìa khóa", openUnlimited: "Mở rương vô hạn lần", dishCount: "MÓN", chooseBanner: "Chọn banner thành tựu", completed: "Đã hoàn thành", limitedCollection: "Bộ sưu tập theo event", collectionSet: "Bộ sưu tập món", openedDishes: "Món đã mở", bestStreak: "Streak tốt nhất", questsSolved: "Quest đã giải", notUnlocked: "CHƯA MỞ", editLabel: "Sửa Label / rarity", label: "Label món", rarity: "Rarity món", saveChanges: "Lưu", undo: "Hủy",
  },
  en: {
    chest: "Taste Chest", collection: "Collection", achievements: "Achievements", wheel: "Wheel", settings: "Settings",
    today: "Today", checkIn: "Check in for keys", checkedIn: "Checked in", comeBackTomorrow: "Come back tomorrow",
    keys: "keys", rewards: "rewards", fusions: "fusions", dailyQuest: "QUESTS EVERY 3 HOURS", limitedEvent: "LIMITED EVENT", weeklyEvent: "WEEKLY EVENT",
    freeChest: "Free chest", collectionFoods: "Food collection", extendedAchievements: "EXTENDED ACHIEVEMENTS", achievementProfile: "Achievement profile", streak: "Day streak",
    sound: "Ritual sound", reducedMotion: "Reduced motion", language: "Language", vietnamese: "Tiếng Việt", english: "English",
    addDish: "Add local dish", catalog: "Food data source", keyHistory: "Key history", save: "Save", close: "Close", cancel: "Cancel", mealBreakfast: "Breakfast", mealLunch: "Lunch", mealDinner: "Dinner", dailyOnce: "Once a day", soundOn: "Turn sound off", soundOff: "Turn sound on", unlimitedChest: "Unlimited chest", keyShort: "KEY", deleteDish: "Delete dish", replaceImage: "Replace image", uploadingImage: "Processing image...", confirmDelete: "Delete this dish from the local catalog?",
    brandTitle: "TASTE CHEST", brandSubtitle: "Open a chest, choose a dish", useLocation: "Use my current location", locationLoading: "Getting your location...", locationDenied: "Location permission was denied.", locationError: "Could not get your location.", enterArea: "Enter an area to search:", tryAgain: "Try again", search: "Search", nearbyRestaurants: "Near your location", findRestaurants: "Find nearby restaurants", openMaps: "Open Maps", directions: "Directions", openNow: "Open now", nearTwoKm: "≤ 2 km", noPlaces: "No restaurants match the criteria.", noFilterResults: "No restaurants match the filters.", clearFilters: "Clear filters", mapsFallback: "Open Maps instead", locationSearchPlaceholder: "District, city...", unknownRating: "No rating/reviews", dataFromOsm: "OpenStreetMap data · ratings/reviews are not available.", dataFromGoogle: "Data from Google Maps", openMapLink: "Search on Google Maps →", openAgain: "Open again", noKeysCheckIn: "Out of keys · Check in tomorrow for more",
    sunrise: "SUNRISE", sunriseSubtitle: "A delicious start to the day", daylight: "DAYLIGHT", daylightSubtitle: "Refuel for the day", dusk: "DUSK", duskSubtitle: "Close the day with a worthy choice", readyState: "Ready to open", keyFlight: "Key resonance", inserting: "Activating the taste core", locking: "Ancient lock aligned", charging: "Gathering energy", pulse: "Peak resonance", anticipation: "Listen for the awakening", impact: "Open!", opening: "Chest opened", rewardRise: "Summoning dish", result: "Reward received", chestHeading: "AWAKEN YOUR", chestHeadingYour: "CHOICE", openChest: "OPEN CHEST", energyGathering: "Energy is converging", unlimitedCost: "UNLIMITED PRIVILEGE · NO KEY COST", keyCost: "COSTS 1 KEY", skipScene: "Skip animation", skipNext: "Skip animation next time", todayDishes: "TODAY", dishes: "DISHES", rarityRate: "RARITY RATE", viewOdds: "VIEW ODDS", goldenHour: "GOLDEN HOUR · Rare+ dish chance increased from 18:00–21:00", freeChestReady: "Free chest today", freeChestUsed: "Free chest already used", noKey: "No key cost", returnTomorrow: "Come back tomorrow", open: "OPEN", share: "Share", favorite: "Favorite", favorited: "Favorited", fusion: "Fusion", unlockedReward: "REWARD UNLOCKED", copyResult: "Result copied!", shareError: "Could not share the result.", downloadCard: "Card", downloadedCard: "Share card downloaded!", dismiss: "Close", retrySearch: "Try again later or open Google Maps.", placeSearchTitle: "Restaurants for", filterDataNote: "Open and distance filters still work.", restaurantOpen: "Open", restaurantClosed: "Closed", loadingRestaurants: "Finding good restaurants near you...", collectionJourney: "COLLECTION JOURNEY", achievementTitle: "Taste Chest Achievements", achievementDescription: "Open each dish at least once. Complete the catalog to unlock unlimited chests on this device.", unlimitedUnlocked: "UNLIMITED CHEST UNLOCKED", wholeReward: "FULL COLLECTION REWARD", noKeyCost: "No more key costs", openUnlimited: "Open unlimited chests", dishCount: "DISHES", chooseBanner: "Choose achievement banner", completed: "Completed", limitedCollection: "Event collection", collectionSet: "Dish collection", openedDishes: "Dishes opened", bestStreak: "Best streak", questsSolved: "Quests solved", notUnlocked: "NOT OPENED", editLabel: "Edit label / rarity", label: "Dish label", rarity: "Dish rarity", saveChanges: "Save", undo: "Cancel",
  },
} as const

export type TranslationKey = keyof typeof translations.vi

export function useLanguage() {
  const language = useAppStore((state) => state.user.preferences.language ?? "vi") as Language
  const updatePreference = useAppStore((state) => state.updatePreference)
  const t = (key: TranslationKey) => translations[language][key]
  return { language, t, setLanguage: (next: Language) => updatePreference("language", next) }
}
