import type { UnitDef, AutoSchool, Skill, Profession } from "./types"
import { getFoodAssetUrl } from "../../infrastructure/assets/foodAssets"

export const AUTO_SCHOOLS: Record<AutoSchool, {
  name: string
  color: string
  text: string
}> = {
  ember: {
    name: "Hỏa vị",
    color: "#ffae70",
    text: "2: đòn đánh đốt 8/s · 4: đốt 16/s",
  },
  tide: {
    name: "Hải vị",
    color: "#79d9ed",
    text: "2: +4 mana mỗi đòn · 4: +8 mana",
  },
  grove: {
    name: "Thanh vị",
    color: "#a4e1af",
    text: "2: hồi 3% mỗi 5s · 4: hồi 6%, giảm choáng",
  },
  hearth: {
    name: "Gia vị",
    color: "#f8d284",
    text: "2: +100 khiên tuyến trước · 4: +220 khiên",
  },
  sugar: {
    name: "Ngọt vị",
    color: "#e2b4f3",
    text: "2: cast cho 70 khiên · 4: cho 150 khiên",
  },
}
export const PROFESSIONS: Record<Profession, { name: string; text: string }> = {
  keeper: { name: "Giữ bếp", text: "2/3: +12/24 giáp" },
  traveler: { name: "Lữ khách", text: "2/3: đi nhanh hơn, +8%/16% công" },
  storyteller: { name: "Người kể", text: "2/3: bắt đầu +15/30 mana" },
}
type Row = [string, string, string, number, AutoSchool, Profession, Skill, number, number, string, string, number, string?]
const rows: Row[] = [
  [
    "pho-bo",
    "Phở bò",
    "Long Ngư Hơi Nước",
    1,
    "tide",
    "storyteller",
    "steam",
    3,
    130,
    "Hơi nhớ xuyên một tuyến, gây 130 sát thương phép.",
    "Hơi nước giữ tiếng gọi bên nồi nước dùng.",
    1,
    "pho-bo",
  ],
  [
    "banh-mi",
    "Bánh mì",
    "Hồ Ly Vỏ Giòn",
    1,
    "ember",
    "traveler",
    "flame",
    1,
    145,
    "Bùng lửa vào mục tiêu, gây 145 phép và đốt 4 giây.",
    "Tiếng vỏ bánh giòn đánh thức sạp sáng sớm.",
    0,
    "banh-mi",
  ],
  [
    "com-tam",
    "Cơm tấm",
    "Sư Tử Gạo Ấm",
    1,
    "hearth",
    "keeper",
    "shield",
    1,
    200,
    "Tạo 200 khiên cho mình và đồng minh gần nhất.",
    "Những hạt gạo nhỏ cũng làm nên một bữa cơm đủ đầy.",
    3,
    "com-tam",
  ],
  [
    "bun-cha",
    "Bún chả",
    "Hồ Ly Than Thơm",
    2,
    "ember",
    "keeper",
    "cleave",
    1,
    170,
    "Quét các địch cạnh mình, gây 170 sát thương vật lý.",
    "Một bếp than gọi khách ngồi lại cùng nhau.",
    0,
    "bun-cha",
  ],
  [
    "bun-rieu",
    "Bún riêu",
    "Giáp Cua Cà Chua",
    2,
    "tide",
    "storyteller",
    "drain",
    3,
    160,
    "Gây 160 phép, hút 30 mana mục tiêu về mình.",
    "Bát riêu nhớ đôi tay khéo vớt từng mảng cua.",
    1,
    "bun-rieu",
  ],
  [
    "banh-xeo",
    "Bánh xèo",
    "Hỏa Điểu Vầng Giòn",
    3,
    "ember",
    "traveler",
    "cone",
    1,
    230,
    "Phóng lửa hình nón về tuyến trước, gây 230 phép.",
    "Tiếng xèo vui vang lên trước cả lời mời.",
    0,
    "banh-xeo",
  ],
  [
    "banh-cuon",
    "Bánh cuốn",
    "Ngọc Thố Hơi Mỏng",
    1,
    "grove",
    "storyteller",
    "heal",
    3,
    170,
    "Chữa 170 máu cho đồng minh thấp tỷ lệ máu nhất.",
    "Từng lớp bánh mỏng được trao bằng sự kiên nhẫn.",
    2,
    "banh-cuon",
  ],
  [
    "goi-cuon",
    "Gỏi cuốn",
    "Linh Lộc Cuộn Lá",
    2,
    "grove",
    "traveler",
    "leaves",
    2,
    160,
    "Bọc lá cho hai đồng minh: 160 khiên và hồi 80 máu.",
    "Một cuốn nhỏ giữ nhiều hương vị cạnh nhau.",
    2,
    "goi-cuon-tom-thit",
  ],
  [
    "xoi",
    "Xôi mặn",
    "Gấu Nếp Mới",
    2,
    "hearth",
    "keeper",
    "stun",
    1,
    150,
    "Húc 150 vật lý, làm choáng mục tiêu 1 giây.",
    "Gói xôi ấm cho người vội vẫn là một lời chăm sóc.",
    3,
    "xoi",
  ],
  [
    "com-ga",
    "Cơm gà",
    "Kim Kê Cánh Nắng",
    3,
    "hearth",
    "traveler",
    "charge",
    1,
    240,
    "Lao dọc hàng, gây 240 vật lý và choáng ngắn.",
    "Nồi cơm vàng giữ ánh nắng sau phiên chợ.",
    3,
    "com-ga",
  ],
  [
    "banh-chung",
    "Bánh chưng",
    "Linh Quy Lá Vuông",
    4,
    "hearth",
    "keeper",
    "shell",
    1,
    350,
    "Nhận 350 khiên, phản 70 phép vào địch cạnh mình.",
    "Buộc lạt là lúc câu chuyện chuyền từ tay này sang tay khác.",
    3,
    "banh-chung",
  ],
  [
    "banh-tet",
    "Bánh tét",
    "Ngọc Thố Nếp Đoàn Viên",
    4,
    "sugar",
    "keeper",
    "feast",
    2,
    260,
    "Hồi 260 máu cho đồng minh quanh mình và cho 100 khiên.",
    "Đòn bánh được chia thành từng khoanh để mời thêm một người.",
    4,
    "banh-tet",
  ],
  [
    "chef-nhien",
    "Nhiên",
    "Người giữ than",
    3,
    "ember",
    "storyteller",
    "flame",
    3,
    280,
    "Lửa 280 phép, đốt cả địch đứng sát mục tiêu.",
    "Nhiên giữ bếp cho người đến muộn.",
    5,
  ],
  [
    "chef-hai",
    "Hải",
    "Người nghe nước",
    4,
    "tide",
    "storyteller",
    "mana",
    3,
    240,
    "Sóng 240 phép; tiếp 20 mana cho hai đồng đội.",
    "Hải nghe câu chuyện trong hơi nước.",
    5,
  ],
  [
    "chef-moc",
    "Mộc",
    "Người giữ lá",
    3,
    "grove",
    "storyteller",
    "ginger",
    3,
    200,
    "Rải vùng lá: hồi 200 máu và giải choáng đồng đội gần mục tiêu.",
    "Mộc nhớ ai từng gieo hạt cho bữa cơm.",
    5,
  ],
  [
    "chef-bach",
    "Bách",
    "Người giữ bàn",
    4,
    "hearth",
    "keeper",
    "lantern",
    1,
    300,
    "Trao 300 khiên cho các đồng minh cùng hàng.",
    "Một chiếc ghế chưa dùng vẫn là lời mời.",
    5,
  ],
  [
    "chef-lien",
    "Liên",
    "Người dệt sao",
    5,
    "sugar",
    "storyteller",
    "feast",
    3,
    400,
    "Hồi 400 máu quanh đồng minh thấp máu và thêm khiên.",
    "Liên cất một điều ước trong vị ngọt.",
    5,
  ],
  [
    "ferry",
    "Lái đò sương bạc",
    "Người đưa khách",
    5,
    "tide",
    "traveler",
    "dash",
    3,
    420,
    "Dòng nước quét một hàng 420 phép, mỗi địch chỉ trúng một lần.",
    "Có người chèo để không ai lạc lại giữa sương.",
    5,
  ],
  [
    "banh-dau-xanh",
    "Bánh đậu xanh",
    "Tiểu Tượng Ngọc",
    1,
    "sugar",
    "keeper",
    "shield",
    1,
    180,
    "Che đồng minh thấp máu 180 khiên.",
    "Miếng bánh nhỏ được dành cho khách ghé thăm.",
    4,
    "banh-dau-xanh",
  ],
  [
    "banh-khuc",
    "Bánh khúc Hà Nội",
    "Mầm Áo Lá",
    1,
    "grove",
    "keeper",
    "leaves",
    1,
    190,
    "Quấn lá cho hai đồng minh, giảm áp lực đòn đầu.",
    "Lời rao đêm khơi lại ký ức con phố.",
    2,
    "banh-khuc",
  ],
  [
    "banh-can",
    "Bánh căn",
    "Chim Than Tròn",
    2,
    "ember",
    "traveler",
    "cone",
    2,
    180,
    "Lấy đà rồi quét lửa hình nón 180 phép.",
    "Bánh vừa ra khuôn, người bên bếp đã mời khách.",
    0,
    "banh-can",
  ],
  [
    "banh-tom-ho-tay",
    "Bánh tôm Hồ Tây",
    "Tôm Lửa Hồ",
    2,
    "tide",
    "traveler",
    "dash",
    2,
    200,
    "Vệt nước quét hàng mục tiêu, gây 200 phép.",
    "Vỏ giòn và rau mát cùng giữ một buổi chiều bên hồ.",
    1,
    "banh-tom-ho-tay",
  ],
  [
    "com-hen",
    "Cơm hến",
    "Linh Trai Sông",
    2,
    "hearth",
    "keeper",
    "shell",
    1,
    260,
    "Khép vỏ nhận 260 khiên, phản đòn vào địch cạnh mình.",
    "Những nguyên liệu giản dị góp thành bát cơm nhiều sắc vị.",
    3,
    "com-hen",
  ],
  [
    "che-lam",
    "Chè lam",
    "Hươu Mật Gừng",
    2,
    "sugar",
    "storyteller",
    "ginger",
    3,
    175,
    "Vùng gừng hồi 175 máu, giải và giảm choáng.",
    "Vị gừng giữ hơi ấm bên chén trà.",
    2,
    "che-lam",
  ],
  [
    "chao-luon",
    "Cháo lươn",
    "Long Tuyến Ấm",
    3,
    "tide",
    "storyteller",
    "steam",
    3,
    270,
    "Hơi nước xuyên tuyến 270 phép; +5 mana mỗi địch trúng.",
    "Bát cháo trao cho người cần một buổi sáng ấm.",
    1,
    "chao-luon",
  ],
  [
    "banh-it-la-gai",
    "Bánh ít lá gai",
    "Dơi Lá Tím",
    3,
    "grove",
    "traveler",
    "dodge",
    2,
    230,
    "Né đòn trong 1 giây, hồi 230 máu đồng minh thấp nhất.",
    "Lớp lá được mở ra để mời một người cùng ăn.",
    2,
    "banh-it-la-gai",
  ],
  [
    "banh-ram-it",
    "Bánh ram ít",
    "Song Linh Giòn Mềm",
    4,
    "hearth",
    "keeper",
    "stun",
    1,
    300,
    "Hai nhịp húc: 300 vật lý, choáng 1 giây; che mình 160 khiên.",
    "Giòn và mềm có chỗ đứng trong cùng một món.",
    3,
    "banh-ram-it",
  ],
  [
    "keo-cu-do",
    "Kẹo cu đơ",
    "Ngưu Lạc Vàng",
    4,
    "ember",
    "keeper",
    "charge",
    1,
    330,
    "Húc xuyên hàng 330 vật lý, choáng các mục tiêu 0,7 giây.",
    "Lạc, mật và bánh tráng giữ tiếng chuyện bên bàn.",
    6,
    "keo-cu-do",
  ],
  [
    "loc",
    "Ông Lộc",
    "Người thắp đèn",
    2,
    "hearth",
    "keeper",
    "lantern",
    2,
    220,
    "Đặt đèn trao 220 khiên cho một hàng đồng minh.",
    "Một chiếc đèn được sửa để câu chuyện tiếp tục sáng.",
    5,
  ],
  [
    "tinh",
    "Tịnh",
    "Người giữ nhịp",
    3,
    "tide",
    "storyteller",
    "rhythm",
    3,
    180,
    "Gõ nhịp 180 phép; +25 mana cho đồng đội cạnh mình.",
    "Một người có thể học lại cách lắng nghe.",
    5,
  ],
  [
    "sen",
    "Bà Sen",
    "Bếp cho khách lạ",
    3,
    "grove",
    "keeper",
    "feast",
    2,
    240,
    "Nấu vùng hồi 240 máu, che đồng đội 90 khiên.",
    "Bà luôn nấu thêm một phần cho người chưa tới.",
    5,
  ],
  [
    "recorder",
    "Người chép chuyện",
    "Trang sổ còn mở",
    5,
    "sugar",
    "storyteller",
    "copy",
    3,
    320,
    "Dùng kỹ năng đồng đội vừa tung với 65% sức mạnh.",
    "Chú giải cũng xứng đáng ở lại trên trang giấy.",
    5,
  ],
]
// Stable IDs keep earlier sessions on their original recruitment pool.
export const LEGACY_UNIT_IDS = new Set(rows.map(row => row[0]))
rows.push(
  ["xoi-xeo", "Xôi xéo", "Tê Tê Nếp Vàng", 1, "hearth", "keeper", "stun", 1, 135, "Húc 135 vật lý, làm choáng mục tiêu 1 giây.", "Gói lá chuối giữ bữa sáng ấm của người đi làm.", 3, "xoi-xeo"],
  ["dua-hanh", "Dưa hành", "Ngọc Thố Muối Xuân", 1, "grove", "storyteller", "ginger", 3, 120, "Hồi 120 máu và giải choáng trong vùng quanh đồng minh yếu nhất.", "Một đĩa nhỏ làm mâm Tết bớt ngấy và lời chuyện thêm dài.", 2, "dua-hanh"],
  ["bun-bo-hue", "Bún bò Huế", "Ngưu Vương Sả Ớt", 2, "ember", "keeper", "cleave", 1, 185, "Quét địch cạnh mình, gây 185 sát thương vật lý.", "Hương sả gọi về những buổi sáng bên dòng Hương.", 0, "bun-bo-hue"],
  ["che-buoi", "Chè bưởi", "Hải Ly Hương Bưởi", 2, "sugar", "storyteller", "mana", 3, 175, "Bắn 175 phép; hai đồng minh yếu máu nhất nhận 20 mana.", "Cùi bưởi giòn và nước cốt dừa giữ một lời mời ngày nắng.", 4, "che-buoi"],
  ["bun-ca", "Bún cá", "Bói Cá Sóng Bạc", 3, "tide", "storyteller", "frost", 3, 240, "Gây 240 phép lên mục tiêu và làm choáng 1 giây.", "Mùi thì là theo gió từ bến cá vào phố chợ.", 1, "bun-ca"],
  ["cha-ruoi", "Chả rươi", "Sóc Lá Thu", 3, "ember", "traveler", "dash", 1, 255, "Chém xuyên một hàng địch, gây 255 sát thương phép.", "Mùa rươi ngắn; những cuộc gặp mùa thu ở lại lâu hơn.", 0, "cha-ruoi"],
  ["cha-ca-la-vong", "Chả cá Lã Vọng", "Lão Ngư Thì Là", 4, "tide", "keeper", "steam", 2, 315, "Hơi thơm xuyên một cột, gây 315 sát thương phép.", "Chảo cá còn nóng là lời mời mọi người cùng ngồi xuống.", 1, "cha-ca-la-vong"],
  ["thit-kho-trung", "Thịt kho trứng", "Huyền Quy Nồi Tết", 4, "hearth", "keeper", "shield", 1, 450, "Tạo 450 khiên cho hai đồng minh yếu máu nhất.", "Nồi kho để dành giữ chỗ cho người nhà trở về.", 3, "thit-kho-trung"],
  ["bun-thang", "Bún thang", "Bạch Hạc Chỉ Vàng", 5, "tide", "storyteller", "steam", 4, 390, "Hơi nước xuyên một cột, gây 390 sát thương phép.", "Nhiều nguyên liệu nhỏ cùng làm nên một bát hài hòa.", 1, "bun-thang"],
  ["com-lang-vong", "Cốm Làng Vòng", "Kỳ Lân Lúa Non", 5, "grove", "keeper", "feast", 2, 370, "Vùng lá cốm hồi 370 máu và tạo 130 khiên cho đồng minh.", "Lá sen và lúa non giữ ký ức mùa thu Hà Nội.", 2, "com-lang-vong"],
  ["banh-com-hang-than", "Bánh cốm Hàng Than", "Yến Ngọc Tơ Duyên", 5, "sugar", "traveler", "copy", 3, 360, "Dùng kỹ năng đồng đội vừa tung với 65% sức mạnh.", "Hộp bánh trao tay giữ lời chúc đôi lứa và ngày sum họp.", 4, "banh-com-hang-than"],
  ["ca-phe-trung", "Cà phê trứng", "Cầy Hương Mây Kem", 5, "hearth", "storyteller", "rhythm", 3, 345, "Gõ nhịp 345 phép; +25 mana cho đồng đội cạnh mình.", "Một chiếc phin nhỏ nối nhịp trò chuyện giữa phố đông.", 3, "ca-phe-trung"],
)
export const AUTO_UNITS: UnitDef[] = rows.map(
  (
    [
      id,
      name,
      spirit,
      cost,
      school,
      profession,
      skill,
      range,
      power,
      text,
      lore,
      sprite,
      foodId,
    ],
    portrait,
  ) => ({
    id,
    name,
    spirit,
    cost,
    school,
    profession,
    skill,
    range,
    power,
    text,
    lore,
    sprite,
    portrait,
    foodId,
    hp:
      (profession === "keeper" ? 760 : profession === "traveler" ? 600 : 480) +
      cost * 80,
    attack: 42 + cost * 10 + (profession === "traveler" ? 8 : 0),
    armor: profession === "keeper" ? 28 : 12,
    interval: profession === "traveler" ? 19 : 23,
    art: foodId
      ? (getFoodAssetUrl(foodId) ?? `/assets/food/full/${foodId}.webp`)
      : "/assets/autochess/roster.webp",
  }),
)
export const UNIT_MAP = Object.fromEntries(AUTO_UNITS.map((u) => [u.id, u]))
export const RELICS = [
  {
    id: "lantern",
    name: "Đèn Dầu Giữ Chỗ",
    text: "Dưới 35% máu: nhận 250 khiên, một lần/vòng.",
    color: "#ffd483",
  },
  {
    id: "ladle",
    name: "Muôi Đồng",
    text: "Mỗi lần cast: hoàn 20 mana.",
    color: "#9fddf5",
  },
  {
    id: "herbs",
    name: "Túi Lá Thơm",
    text: "+100 máu, thời gian choáng giảm 50%.",
    color: "#afe9a0",
  },
  {
    id: "bell",
    name: "Chuông Chợ",
    text: "Đứng cạnh đồng minh khi xuất trận: +18% công.",
    color: "#f4c27b",
  },
  {
    id: "basket",
    name: "Giỏ Tre",
    text: "+180 máu, đi nhanh hơn 20%.",
    color: "#d9c49b",
  },
  {
    id: "book",
    name: "Sổ Công Thức Trống",
    text: "Kỹ năng đầu tiên mỗi vòng mạnh hơn 45%.",
    color: "#e2b4f3",
  },
]
export const AUGMENTS = [
  {
    id: "guests",
    name: "Bếp có khách",
    text: "Đội có ít nhất 3 hệ khác nhau: toàn đội +15% máu.",
  },
  {
    id: "seat",
    name: "Giữ một chỗ",
    text: "Quân không đứng sát đồng minh: +25% công khi xuất trận.",
  },
  {
    id: "together",
    name: "Nấu cùng nhau",
    text: "Quân đứng cạnh đồng minh: +120 khiên khi xuất trận.",
  },
  {
    id: "shift",
    name: "Đổi phiên",
    text: "Một lần đổi cửa hàng miễn phí mỗi vòng.",
  },
  {
    id: "last-light",
    name: "Đèn cuối phố",
    text: "Ý chí dưới 45: toàn đội +180 khiên khi xuất trận.",
  },
  {
    id: "another",
    name: "Kể thêm một chuyện",
    text: "Được đổi một lựa chọn di vật và +2 vàng mỗi vòng.",
  },
]
export const COSMETICS = [
  { id: "river", name: "Sân bếp bên sông", cost: 60, scene: 1 },
  { id: "archive", name: "Thư quán trong sương", cost: 120, scene: 2 },
  { id: "dawn", name: "Bàn đón bình minh", cost: 200, scene: 3 },
]
export interface MonsterDef {
  id: string
  name: string
  hp: number
  attack: number
  range: number
  armor: number
  skill: Skill
  power: number
  school: AutoSchool
  sprite: number
  text: string
  boss?: boolean
  unlockWave?: number
}
export const MONSTERS: MonsterDef[] = [
  {
    id: "mist",
    name: "Hạt Sương Lạc",
    hp: 400,
    attack: 34,
    range: 1,
    armor: 8,
    skill: "steam",
    power: 80,
    school: "tide",
    sprite: 0,
    text: "Cận chiến cơ bản. Giữ tuyến trước bảo vệ carry.",
  },
  {
    id: "rat",
    name: "Chuột Tro",
    hp: 420,
    attack: 44,
    range: 1,
    armor: 5,
    skill: "charge",
    power: 110,
    school: "ember",
    sprite: 1,
    text: "Săn quân tầm xa. Đặt hộ vệ cạnh carry.",
  },
  {
    id: "beetle",
    name: "Bọ Mực Nhạt",
    hp: 500,
    attack: 35,
    range: 3,
    armor: 10,
    skill: "drain",
    power: 120,
    school: "sugar",
    sprite: 2,
    text: "Hút mana theo đường nối. Ưu tiên hạ trước.",
  },
  {
    id: "straw",
    name: "Bóng Rơm",
    hp: 850,
    attack: 38,
    range: 1,
    armor: 40,
    skill: "shell",
    power: 180,
    school: "hearth",
    sprite: 3,
    text: "Giáp vật lý cao. Phép xuyên được lớp phòng thủ.",
  },
  {
    id: "mushroom",
    name: "Nấm Quên",
    hp: 550,
    attack: 32,
    range: 3,
    armor: 8,
    skill: "feast",
    power: 120,
    school: "grove",
    sprite: 4,
    text: "Hồi máu đồng đội gần. Dồn sát thương hoặc đánh nhanh.",
  },
  {
    id: "fish",
    name: "Cá Hơi Lạnh",
    hp: 500,
    attack: 52,
    range: 3,
    armor: 8,
    skill: "frost",
    power: 150,
    school: "tide",
    sprite: 5,
    text: "Đạn lạnh làm choáng. Dùng Túi Lá Thơm hoặc Thanh vị.",
  },
  {
    id: "ladle-puppet",
    name: "Rối Muôi Gãy",
    hp: 650,
    attack: 44,
    range: 2,
    armor: 15,
    skill: "stun",
    power: 180,
    school: "hearth",
    sprite: 6,
    text: "Có niệm choáng rõ ràng. Tản đội, dùng hồi/khiên.",
  },
  {
    id: "bat",
    name: "Dơi Chữ Rơi",
    hp: 480,
    attack: 50,
    range: 2,
    armor: 8,
    skill: "dodge",
    power: 120,
    school: "grove",
    sprite: 7,
    text: "Né 1 giây sau cast. Không dồn cả đội vào một mục tiêu.",
  },
  {
    id: "bull",
    name: "Trâu Giấy Nhạt",
    hp: 1000,
    attack: 46,
    range: 1,
    armor: 35,
    skill: "charge",
    power: 200,
    school: "ember",
    sprite: 8,
    text: "Húc hàng và chịu đòn. Tản carry, phép hoặc hồi bền.",
  },
  {
    id: "nameless",
    name: "Người Không Tên",
    hp: 750,
    attack: 52,
    range: 3,
    armor: 16,
    skill: "copy",
    power: 210,
    school: "sugar",
    sprite: 9,
    text: "Phản chiếu skill vừa dùng, không sao chép toàn bộ đội hình.",
  },
  {
    id: "empty-lantern",
    name: "Rối Đèn Rỗng",
    hp: 1600,
    attack: 55,
    range: 2,
    armor: 20,
    skill: "cone",
    power: 240,
    school: "ember",
    sprite: 10,
    text: "Boss: báo vùng lửa trước khi đánh. Dưới 50% máu chuyển pha.",
    boss: true,
  },
  {
    id: "white-ink",
    name: "Mực Trắng",
    hp: 1900,
    attack: 58,
    range: 3,
    armor: 20,
    skill: "copy",
    power: 260,
    school: "sugar",
    sprite: 11,
    text: "Boss: phản chiếu kỹ năng, pha hai hút mana.",
    boss: true,
  },
  {
    id: "one-color",
    name: "Người Chép Một Màu",
    hp: 2300,
    attack: 62,
    range: 3,
    armor: 24,
    skill: "seal",
    power: 230,
    school: "tide",
    sprite: 12,
    text: "Boss: phong ấn kỹ năng một hệ 3 giây. Đội đa hệ vẫn chiến đấu.",
    boss: true,
  },
  {
    id: "unwritten",
    name: "Trang Cuối Chưa Viết",
    hp: 2900,
    attack: 66,
    range: 3,
    armor: 24,
    skill: "summon",
    power: 220,
    school: "sugar",
    sprite: 13,
    text: "Boss: gọi linh ảnh, ba pha; quái gọi thêm không cho điểm riêng.",
    boss: true,
  },
]
export const LEGACY_MONSTER_COUNT = MONSTERS.length
MONSTERS.push(
  { id: "ink-crab", name: "Cua Mực Nhạt", hp: 720, attack: 42, range: 1, armor: 30, skill: "shell", power: 210, school: "tide", sprite: 0, unlockWave: 3, text: "Khép vỏ tạo khiên. Dùng sát thương phép để vượt giáp." },
  { id: "char-hound", name: "Chó Than", hp: 610, attack: 59, range: 1, armor: 9, skill: "cone", power: 190, school: "ember", sprite: 1, unlockWave: 4, text: "Lửa hình nón phạt đội hình đứng sát. Tách carry khỏi tuyến trước." },
  { id: "silk-moth", name: "Bướm Chỉ Lạc", hp: 560, attack: 38, range: 3, armor: 10, skill: "drain", power: 165, school: "sugar", sprite: 2, unlockWave: 5, text: "Hút mana mục tiêu. Dùng Lữ khách áp sát trước khi niệm phép." },
  { id: "bamboo-wraith", name: "Trúc Khô", hp: 790, attack: 40, range: 2, armor: 24, skill: "leaves", power: 180, school: "grove", sprite: 3, unlockWave: 6, text: "Bọc lá tiếp sức đồng đội. Hạ quân hỗ trợ trước khi đánh tank." },
  { id: "rival-ladle", name: "Người Bếp Không Tên", hp: 850, attack: 56, range: 1, armor: 20, skill: "lantern", power: 230, school: "hearth", sprite: 0, unlockWave: 7, text: "Đối thủ giữ bếp trao khiên cả hàng. Tấn công từ nhiều tuyến." },
  { id: "rival-flute", name: "Kẻ Giấu Tiếng Sáo", hp: 650, attack: 47, range: 3, armor: 12, skill: "rhythm", power: 205, school: "tide", sprite: 1, unlockWave: 8, text: "Nhịp sáo gây phép và tiếp mana. Chặn nhịp bằng choáng hoặc khóa phép." },
  { id: "boss-drum", name: "Vọng Trống Lạc Nhịp", hp: 2600, attack: 84, range: 1, armor: 28, skill: "stun", power: 345, school: "hearth", sprite: 2, boss: true, text: "Boss Survival: tiếng vọng bị sương làm lệch nhịp, choáng tuyến trước. Thanh vị giảm thời gian choáng." },
  { id: "boss-lotus", name: "Sen Sương Khép Cánh", hp: 3100, attack: 81, range: 3, armor: 22, skill: "seal", power: 320, school: "grove", sprite: 3, boss: true, text: "Boss Survival: khóa phép người đứng trước, chuyển pha dưới nửa máu. Cần cả đòn đánh và phép." },
)
export const MONSTER_MAP = Object.fromEntries(MONSTERS.map((m) => [m.id, m]))
export const SKILL_LABELS: Record<Skill, string> = {
  flame: "Bùng hương",
  steam: "Hơi nhớ",
  shield: "Giữ chỗ",
  heal: "Bát ấm",
  cleave: "Quét than",
  dash: "Dòng chảy",
  leaves: "Áo lá",
  mana: "Tiếp nhịp",
  cone: "Vầng lửa",
  shell: "Khép vỏ",
  ginger: "Vùng gừng",
  dodge: "Lướt lá",
  charge: "Húc vị",
  lantern: "Thắp đèn",
  rhythm: "Gõ nhịp",
  feast: "Mời cơm",
  copy: "Chép chuyện",
  drain: "Hút mực",
  stun: "Giữ chân",
  summon: "Gọi linh ảnh",
  seal: "Một màu",
  frost: "Hơi lạnh",
}
export const LEGACY_SHOP_ODDS = [
  [75, 25, 0, 0, 0],
  [55, 35, 10, 0, 0],
  [35, 35, 25, 5, 0],
  [20, 30, 35, 13, 2],
  [10, 20, 35, 25, 10],
]
export const SHOP_ODDS = [
  [75, 25, 0, 0, 0],
  [55, 30, 15, 0, 0],
  [40, 35, 23, 2, 0],
  [25, 35, 30, 10, 0],
  [15, 25, 30, 25, 5],
]
export const shopOdds = (level: number, rulesVersion: number) =>
  (rulesVersion >= 3 ? SHOP_ODDS : LEGACY_SHOP_ODDS)[Math.max(0, Math.min(4, level - 3))]
