export type PolicyId = "terms" | "privacy" | "rights"
export const POLICY_DATE = "09/10/2026"
export const SUPPORT_URL = "https://github.com/minhutc359-ship-it/MealGacha/issues"
export interface Policy { title: string; intro: string; sections: { title: string; paragraphs: string[] }[] }

export const POLICIES: Record<PolicyId, Policy> = {
  terms: {
    title: "Điều khoản sử dụng",
    intro: "Áp dụng cho Soul of Meal, gồm TCG, Chợ Đêm Auto chess và Rương vị giác. Hãy đọc trước khi chơi; tiếp tục sử dụng nghĩa là bạn đồng ý với những điều khoản phù hợp với pháp luật áp dụng.",
    sections: [
      { title: "1. Quyền chơi và nội dung", paragraphs: ["Soul of Meal cấp cho bạn quyền cá nhân, không độc quyền để chơi phiên bản được cung cấp hợp pháp. Trừ khi có giấy phép riêng, quyền chơi không bao gồm quyền sao chép để bán, phát hành lại, phân phối mã nguồn, nhạc hoặc hình ảnh của trò chơi.", "Trò chơi lấy cảm hứng từ ẩm thực, đời sống và văn hóa Việt Nam. Nhân vật, Vị Linh, hội thoại và các sự kiện kỳ ảo là hư cấu; không đại diện cho một cá nhân, doanh nghiệp hay tín ngưỡng cụ thể."] },
      { title: "2. Tiến trình và vật phẩm ảo", paragraphs: ["Bản hiện tại chạy trên thiết bị, không có tài khoản, giao dịch giữa người chơi hoặc thanh toán trong ứng dụng. Xu, vàng, chìa khóa, thẻ và điểm số là tài nguyên giải trí, không phải tiền, tài sản đầu tư hay quyền nhận tiền thưởng và không đổi thành tiền mặt.", "Tiến trình được lưu cục bộ. Xóa dữ liệu trình duyệt, đổi thiết bị hoặc gỡ ứng dụng có thể làm mất tiến trình. Bạn nên xuất bản lưu trước khi chuyển thiết bị; người giữ nguyên mã tiến trình có thể nhập và sử dụng dữ liệu đó. Cập nhật cân bằng có thể thay đổi chỉ số và cách chơi, nhưng không làm mất các quyền bắt buộc theo pháp luật.", "Nếu bổ sung giao dịch trả phí, ứng dụng phải công bố giá, xác suất phần thưởng ngẫu nhiên nếu có, chính sách hoàn tiền và điều khoản thanh toán tương ứng trước khi giao dịch được thực hiện."] },
      { title: "3. Nội dung do bạn đưa vào", paragraphs: ["Bạn giữ quyền đối với ảnh, thông tin hoặc danh mục tự nhập mà bạn có quyền sử dụng. Chỉ đưa vào nội dung hợp pháp, có sự đồng ý cần thiết và không xâm phạm quyền của người khác. Không đăng mã tiến trình hoặc ảnh riêng tư lên nơi công cộng nếu bạn không muốn người khác tiếp cận.", "Ứng dụng chỉ xử lý nội dung này để cung cấp chức năng trên thiết bị; việc bạn chủ động xuất hoặc chia sẻ không trao quyền sở hữu nội dung đó cho Soul of Meal."] },
      { title: "4. Tìm quán và dịch vụ bên ngoài", paragraphs: ["Kết quả tìm quán dựa trên dữ liệu bên ngoài, có thể thiếu hoặc sai giờ mở cửa, giá, địa chỉ và thông tin liên hệ. Hãy kiểm tra trực tiếp với quán trước khi đi hoặc đặt dịch vụ. Soul of Meal không thu tiền đặt bàn hay đại diện cho các quán.", "Khi mở bản đồ, đường dẫn hỗ trợ hoặc dữ liệu từ địa chỉ bạn tự cấu hình, bạn sử dụng dịch vụ của bên đó theo điều khoản và chính sách riêng của họ."] },
      { title: "5. Sử dụng hợp lý", paragraphs: ["Không dùng ứng dụng để phát tán nội dung trái pháp luật, giả mạo người phát hành, khai thác lỗ hổng gây hại cho người khác hoặc phân phối tài nguyên mà bạn không có quyền. Những giới hạn này không hạn chế các quyền được pháp luật cho phép, kể cả quyền nghiên cứu tương thích khi áp dụng."] },
      { title: "6. Hỗ trợ, thay đổi và quyền người tiêu dùng", paragraphs: ["Ứng dụng được cung cấp theo chức năng được mô tả; không cam kết hoạt động không gián đoạn hoặc dữ liệu bên ngoài luôn chính xác. Nhà phát hành có thể sửa lỗi, thay đổi nội dung và cân bằng, kèm ngày cập nhật điều khoản. Thay đổi quan trọng đối với dữ liệu hoặc thanh toán phải được thông báo trước khi áp dụng khi pháp luật yêu cầu.", "Không điều khoản nào loại bỏ quyền bảo vệ dữ liệu, bảo hành, hoàn tiền hoặc trách nhiệm bắt buộc theo pháp luật áp dụng. Yêu cầu hỗ trợ hoặc khiếu nại được tiếp nhận qua đường dẫn liên hệ ở cuối trang. Việc chuyển nhượng hoặc bán ứng dụng cần một thỏa thuận riêng và không làm mất các quyền này."] },
    ],
  },
  privacy: {
    title: "Chính sách quyền riêng tư",
    intro: "Chính sách này mô tả phiên bản 3.3 hiện tại. Soul of Meal không yêu cầu đăng nhập; tiến trình và ảnh tự nhập được lưu trên thiết bị. Một số chức năng gửi yêu cầu đến dịch vụ bên ngoài khi bạn sử dụng chúng.",
    sections: [
      { title: "1. Dữ liệu trên thiết bị", paragraphs: ["Trình duyệt lưu bộ sưu tập, bộ bài, tiền và chìa khóa ảo, chiến dịch, trận Auto chess, kỷ lục, lịch sử chơi, tên hiển thị và tùy chọn bằng localStorage. Ảnh check-in do bạn thêm được lưu bằng IndexedDB. Ứng dụng sử dụng chúng để tiếp tục trò chơi và hiển thị nội dung bạn đã chọn.", "Nhà phát hành không tự động tải tiến trình hoặc ảnh lên tài khoản máy chủ. Bản ZIP, JSON hoặc mã MGC1 chỉ được tạo và chuyển khi bạn chủ động xuất, sao chép hoặc chia sẻ. Mã MGC1 chứa cả khóa giải mã, vì vậy đây là mã chuyển tiến trình, không phải mật khẩu riêng hay một bản lưu mà người có mã không thể đọc."] },
      { title: "2. Vị trí và tìm quán", paragraphs: ["Ứng dụng chỉ yêu cầu quyền vị trí khi bạn chọn tìm gần đây. Bạn có thể từ chối và nhập khu vực bằng chữ. Vị trí hoặc từ khóa tìm kiếm cần thiết được gửi đến Photon (photon.komoot.io) và Overpass (overpass.private.coffee) để tìm địa điểm từ OpenStreetMap. Các dịch vụ này có thể nhận địa chỉ IP và ghi nhận yêu cầu theo chính sách của họ.", "Ứng dụng giữ bộ nhớ đệm tìm kiếm ngắn hạn trong phiên; không lập lịch theo dõi vị trí nền. Khi bạn chọn chỉ đường hoặc mở Google Maps, Google nhận thông tin điểm đến và yêu cầu của trình duyệt. Nếu một bản triển khai cấu hình nhà cung cấp Google Places thay thế, yêu cầu tìm quán được gửi đến Google thay vì dịch vụ mặc định."] },
      { title: "3. Lưu lượng web và liên kết", paragraphs: ["Vercel phân phối trang, hình và nhạc nên có thể xử lý địa chỉ IP, thông tin yêu cầu và nhật ký kỹ thuật theo chính sách của dịch vụ lưu trữ. Kiểu chữ hiện tại được tải từ Google Fonts; Google có thể nhận địa chỉ IP và thông tin yêu cầu tải font. Bản hiện tại không cài SDK quảng cáo hoặc công cụ phân tích hành vi của nhà phát hành.", "Nếu bạn cấu hình danh mục CSV hoặc URL bên ngoài, trình duyệt kết nối đến địa chỉ đó và dịch vụ tương ứng có thể nhận thông tin yêu cầu. Khi bạn gửi phản hồi công khai qua GitHub, thông tin bạn đăng chịu chính sách của GitHub và có thể được người khác xem."] },
      { title: "4. Kiểm soát, xóa và thời gian lưu", paragraphs: ["Bạn có thể xuất dữ liệu, xóa dữ liệu Rương trong cài đặt chung, hoặc xóa dữ liệu trang trong trình duyệt để xóa toàn bộ lưu trữ cục bộ của cả ba chế độ. Sao lưu trước khi xóa nếu muốn tiếp tục chơi. Bản xuất ở ngoài ứng dụng phải được bạn xóa tại nơi đã lưu hoặc chia sẻ.", "Dữ liệu trên thiết bị tồn tại đến khi bị bạn xóa, trình duyệt thu hồi hoặc ứng dụng bị gỡ. Nhà phát hành không kiểm soát thời gian lưu nhật ký của các dịch vụ bên ngoài. Bạn có thể thu hồi quyền vị trí trong cài đặt trình duyệt; việc này không ngăn các chế độ chiến đấu hoạt động."] },
      { title: "5. Trẻ em, bảo mật và thay đổi", paragraphs: ["Bản hiện tại không yêu cầu tuổi, thông tin định danh hoặc hồ sơ trẻ em và không có trò chuyện công khai. Người giám hộ nên hướng dẫn việc sử dụng vị trí, ảnh và liên kết ngoài. Bản phát hành có quảng cáo, tài khoản hoặc thanh toán phải được cập nhật chính sách và đánh giá yêu cầu theo độ tuổi trước khi mở chức năng đó.", "Mã hóa khi xuất giúp kiểm tra tính toàn vẹn và chuyển tiến trình; ai có mã đầy đủ vẫn có thể đọc nội dung. Không có hệ thống lưu trữ nào bảo đảm an toàn tuyệt đối. Không đặt thông tin nhạy cảm trong tên hiển thị hoặc bản lưu. Mọi thay đổi quan trọng trong cách xử lý dữ liệu sẽ được công bố ở trang này với ngày hiệu lực mới."] },
    ],
  },
  rights: {
    title: "Quyền sử dụng & ghi công",
    intro: "Soul of Meal sử dụng nội dung của dự án và các thư viện theo giấy phép tương ứng. Không tuyên bố mọi tài nguyên là “không có bản quyền”, CC0 hay thuộc phạm vi công cộng.",
    sections: [
      { title: "1. Nội dung của Soul of Meal", paragraphs: ["Quyền đối với mã, cốt truyện, thiết kế, hình và nhạc do dự án tạo được bảo lưu cho chủ thể có quyền, trong phạm vi pháp luật cho phép. Một số hình được tạo với sự hỗ trợ của AI; việc đó không bảo đảm tính độc quyền, khả năng đăng ký bản quyền ở mọi quốc gia hoặc việc không trùng với nội dung của bên khác.", "Các tên món, dữ kiện văn hóa và truyền thống Việt Nam không bị tuyên bố là tài sản độc quyền của ứng dụng. Nhãn hiệu bên thứ ba nếu được nhắc đến chỉ nhằm mô tả; không hàm ý tài trợ hoặc hợp tác."] },
      { title: "2. Thư viện và dữ liệu địa điểm", paragraphs: ["React, React Router, Zustand, Zod, Papa Parse, PixiJS và các phụ thuộc được sử dụng theo giấy phép riêng. GSAP sử dụng Standard License của GSAP/Webflow, không phải MIT. Các thông báo và điều kiện bắt buộc được giữ trong hồ sơ giấy phép của bản phát hành.", "Dữ liệu địa điểm © OpenStreetMap contributors, được cung cấp theo Open Database License (ODbL). Việc sử dụng và phân phối dữ liệu này phải tuân thủ ghi công và nghĩa vụ của ODbL khi áp dụng. Google Fonts và các dịch vụ liên kết có giấy phép hoặc điều khoản riêng."] },
      { title: "3. Phát hành hoặc mua bán ứng dụng", paragraphs: ["Quyền chơi không phải quyền mua mã nguồn hoặc quyền kinh doanh lại ứng dụng. Bên bán cần chuyển giao các quyền mà mình thực sự sở hữu bằng thỏa thuận bằng văn bản, cung cấp hồ sơ tài nguyên và giữ nghĩa vụ giấy phép bên thứ ba. Tên miền, tài khoản cửa hàng, dịch vụ lưu trữ và thương hiệu cần được xử lý riêng trong giao dịch.", "Hồ sơ tài nguyên trong dự án ghi nguồn, dấu vân tay tệp và bằng chứng hiện có để hỗ trợ rà soát. Các tệp cũ đã xác định thiếu bằng chứng giấy phép được chuyển ra ngoài tài nguyên phát hành. Chủ sở hữu vẫn cần hoàn thiện bằng chứng còn thiếu và rà soát quyền của những tài nguyên còn lại trước khi bán hoặc phát hành thương mại. Hồ sơ này không thay thế việc xác minh quyền của tác giả, nhà cung cấp hoặc tư vấn pháp lý trước một giao dịch thương mại."] },
      { title: "4. Báo cáo quyền sở hữu", paragraphs: ["Nếu bạn cho rằng nội dung xâm phạm quyền của mình, hãy gửi đường dẫn hoặc tên tài nguyên, mô tả quyền liên quan, bằng chứng và cách liên hệ qua kênh hỗ trợ. Tránh đăng thông tin cá nhân nhạy cảm ở phản hồi công khai. Nhà phát hành sẽ xem xét, yêu cầu thông tin cần thiết và sửa hoặc gỡ nội dung khi phù hợp."] },
    ],
  },
}
