"""Mechanical atlas registration/encoding. Art and alpha are generated by Imagegen, not drawn here.
Input: JSON {models:{id:absolute_png_path},boss:absolute_png_path}. Retains all 24 actual poses.
"""
from PIL import Image
from pathlib import Path
import numpy as np, json, sys, hashlib
root=Path(__file__).resolve().parents[2]; inputs=json.loads(Path(sys.argv[1]).read_text())
manifest=json.loads((root/'src/game/autochess/spriteFrames.json').read_text());records=[]
folder=root/'public/assets/v4/characters';folder.mkdir(parents=True,exist_ok=True)

def register(id,image,blocks=1):
 a=np.asarray(image.getchannel('A'));projection=(a>180).sum(axis=1)
 # The generator's row gaps are measured, rather than assuming perfect square cells.
 rows=[0]
 for i in range(1,4*blocks):
  ideal=round(i*image.height/(4*blocks));gap=max(4,round(image.height/(4*blocks)*.17))
  window=projection[max(0,ideal-gap):ideal+gap];rows.append(max(0,ideal-gap)+int(np.argmin(window)))
 rows.append(image.height)
 size=128;out=Image.new('RGBA',(size*6,size*4*blocks));entries=[]
 for block in range(blocks):
  frames=[]
  for local in range(24):
   r=block*4+local//6;c=local%6
   left=round(c*image.width/6);right=round((c+1)*image.width/6)
   crop=image.crop((left,rows[r],right,rows[r+1]))
   # Uniform cells preserve authored pose scale; fit with padding and premultiplied-alpha resize.
   scale=min((size-12)/crop.width,(size-12)/crop.height)
   sprite=crop.resize((round(crop.width*scale),round(crop.height*scale)),Image.Resampling.LANCZOS)
   x=(size-sprite.width)//2;y=(size-sprite.height)//2
   out.alpha_composite(sprite,(c*size+x,r*size+y))
   frames.append([c*size,r*size,size,size,size/2,size-6])
  entries.append({'height':size,'frames':frames})
 path=folder/f'{id}.webp';out.save(path,'WEBP',quality=35 if blocks==2 else 55,method=6,exact=True)
 key='living-'+id;manifest[key]={'path':'/assets/v4/characters/'+path.name,'width':out.width,'height':out.height,'rows':entries}
 records.append({'id':id,'sourceSHA256':hashlib.sha256(image.tobytes()).hexdigest(),'posesPerModel':24,'grid':'6x4 per model','rowCuts':rows,'path':str(path.relative_to(root)),'bytes':path.stat().st_size,'decodedBytes':out.width*out.height*4})
if '--only-boss' in sys.argv: records=[m for m in json.loads((root/'dev/docs/major-v400/clip-assets.json').read_text())['models'] if m['id']!='bosses']
for id,filename in ({} if '--only-boss' in sys.argv else inputs['models']).items():register(id,Image.open(filename).convert('RGBA'))
register('bosses',Image.open(inputs['boss']).convert('RGBA'),2)
(root/'src/game/autochess/spriteFrames.json').write_text(json.dumps(manifest,separators=(',',':'))+'\n')
(root/'dev/docs/major-v400/clip-assets.json').write_text(json.dumps({'tool':'Imagegen','method':'original roster pose references; new handpainted pose atlases, measured row gaps and alpha-preserving WebP encoding','models':records},indent=2)+'\n')
print({'models':14,'rasterPoses':336,'bytes':sum(r['bytes'] for r in records)})
